### ISSUE TITLE
Add a readme file

### ISSUE THREAD

**Issue by lakruzz** [Praqma/git-tollgate-plugin#15]
@MadsNielsen @praqma-thi @buep   - who owns this repo?

Please make absolutely sure that this initiative is aligned with the ambition in git-phlow (poke @groenborg ), that some commands are _agent commands_ - expected to run on agents (concourse workers, jenkins slaves, TeamCity workers, bla, bla, bla...)

The idea with the agent-commands is, that no matter how you wanna implement "Pretested Ingtegration" (PiP). at the end of the day, it boils down to a handful of git commands.

We have ordered these commands nicely in batches and made them available - so if you wanna implement a "PiP" - just install the git-phlow extension and run a few commands.

@groenborg and @Sharor already implement a [concourse extension](https://github.com/Praqma/concourse-git-phlow) that utilizes the git phlow. And despite the fact that concourse workers don't support the need for additional git-extensions installed - Simon and David did it anyway, by providing the functions of git-phlow, as a library that was imported; It's still the same code base!

If we're not careful - and collaborate - we might end up reimplementing stuff - stuff that ought to be shared and jointly developed.

So the very short message is: 

**_"This repo needs a README.md file! Who owns this repo?"_**

...Who ever get's to own this, will have to carefully and respectfully coordinate with 

* [concourse-git-phlow](https://github.com/Praqma/concourse-git-phlow)
* [pretested-integration-plugin](https://github.com/Praqma/pretested-integration-plugin)
* [teamcity-merge](https://github.com/debitoor/teamcity-merge) ...Allan Ebdrup (poke: @ebdrup) from Debitoor, implemented the exact same features for TeamCity based on our model - there's room for collaboration here too!

**Comment by praqma-thi** [comment]
I'll take ownership as it was originally my initiative to create it.
This repo is to become an incredibly simple, lightweight, pipeline-compliant, integration tollgate plugin for Jenkins. That's it.

I intend to visit CPH and work on it with Mads for another friday or two to get some polish on it, then consider it done and feature complete.

I'll be adding a README.md clarifying all this soon.

**Comment by praqma-thi** [comment]
I decided to leave plugin politics out of the README, but I fully intend for this plugin to:
 - Replace the Pretested Integration plugin
 - Not make direct use of, but also not be incompatible with the git phlow

It's really just a rebellious move against the stagnancy and bloat of the pretested integration plugin.
